### ISSUE TITLE
Bug ao criar uma petição

### ISSUE THREAD

**Issue by caioitiroko** [itsriodejaneiro/mudamos-web#470]

**Comment by caioitiroko** [comment]
Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.5ms)
NoMethodError (undefined method 'share_link' for nil:NilClass):
app/use_cases/petition_plugin/dynamic_link_metrics.rb:15:in 'perform'
app/controllers/admin/cycles/plugin_relations/petitions_controller.rb:4:in `index’
source=rack-timeout id=50d746679396cd3a8e5e945b0e1f76a7 timeout=29000ms service=18ms state=completed
source=rack-timeout id=76b8f710ee55403d2535a11a626972d7 timeout=29000ms state=ready
Started GET “/api/v2/petitions/6/info” for 189.6.19.221 at 2018-06-21 18:39:07 +0000
